export const SAVE_MEMBER = 'SAVE_MEMBER';
export const UPDATE_MEMBER = 'UPDATE_MEMBER';
export const DELETE_MEMBER = 'DELETE_MEMBER';
export const UPDATE_MEMBER_LOCATION = 'UPDATE_MEMBER_LOCATION'
export const RESET_EVERYTHING = 'RESET_EVERYTHING'
